feat: add home searchbar api logic
GoGo-tm/GoGo_Client pull request #117
Opened 2022-10-30 10:21 UTC by blan19

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feature/home-searchbar

### 변경 사항
홈 서치바에 api 로직을 추가하였습니다

### Issue

resolved: #113

2022-10-30 11:46 UTC, tooooo1 requested changes
어제 오늘 고생하셨어요! ㅎㅎ 같이하니까 더 재미있고 좋네요 ㅋㅋㅋ

2022-10-30 11:46 UTC, tooooo1 commented on components/search.tsx
> +    </>
Base로 묶여서 Flagments 필요 없을거같아보여요! 
혹시 추가하신 다른 이유가 있으실까요?

2022-10-30 11:46 UTC, tooooo1 commented on components/search.tsx
> +    if (data && data.contents && data.contents.length >= 1) {
`if(data?.contents?.length)`는 어떨까요?

2022-10-30 12:59 UTC, tooooo1 commented on components/search.tsx
> +import { useRouter } from 'next/router';
해당 페이지에서 Error가 나고있어요! 그래서 vercel 배포가 안 되는데 확인 한번 부탁드려요

2022-11-01 03:45 UTC, blan19 commented on components/search.tsx
> +    </>
제가 놓친 디테일이 많네요 의도하지 않았던 부분입니다! 바로 반영했어요 ㅋㅋㅋ

2022-11-01 03:46 UTC, blan19 commented on components/search.tsx
> +import { useRouter } from 'next/router';
제가 린트를 꺼놨는지 경고를 못봤네요 ㅋㅋㅋ

2022-11-01 04:00 UTC, merged