Feature banner
GoGo-tm/GoGo_Client pull request #17
Opened 2022-08-15 05:48 UTC by blan19

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feature_banner -> master

### 변경 사항

배너에 필요한 날씨 api 로직을 분리해서 작성했습니다
이 로직으로 react-query 프리페칭, 데이터 페칭 작업이 이루어집니다!

### 테스트 결과

api에 필요한 환경변수는 따로 vercel에 등록해야될 것 같습니다 환경변수 파일은 따로 첨부해서 드리겠습니다~

### Issue

#16

resolved: #

2022-08-15 10:07 UTC, tooooo1 requested changes
오우 작업량..! ㅋㅋㅋ

2022-08-15 10:07 UTC, tooooo1 commented on components/banner.tsx
> +const LandingImage = styled(Image)``;
이거는 불필요한 변수 선언 아닐까요? 바로 넣는건 어때요?

2022-08-15 23:11 UTC, blan19 commented on components/banner.tsx
> +const LandingImage = styled(Image)``;
네이밍 맞출려고 만들어준건데 쓸데없긴 하네요.. 수정하겠습니다~!

2022-08-16 01:22 UTC, tooooo1 approved these changes
좋아요

2022-08-16 01:23 UTC, merged