feat: auth 페이지 및 폴더 구조 변경
GoGo-tm/GoGo_Client pull request #32
Opened 2022-08-22 03:33 UTC by blan19

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feature/auth -> dev

### 변경 사항

로그인/회원가입 페이지 마크업 구현했습니다.
<img width="289" alt="스크린샷 2022-08-22 오후 12 24 26" src="https://user-images.githubusercontent.com/66871265/185832900-6559f930-b6bb-4eb9-a4a5-eeb493ff73d7.png">

<img width="289" alt="스크린샷 2022-08-22 오후 12 27 55" src="https://user-images.githubusercontent.com/66871265/185832909-7cbef288-0ce9-450e-93ae-a77f00e333ef.png">

assets 폴더로 svg 폴더를 옮겨두었습니다!

auth에서 공통으로 겹치는 코드를 훅으로 분리했습니다

### 테스트 결과

### Issue
#28 

resolved: #27

2022-08-22 05:11 UTC, tooooo1 requested changes
작업 많이해주셨네요

2022-08-22 05:11 UTC, tooooo1 commented on components/auth/styled.ts
> +const AuthRadioButton = styled(Radio)``;
이 부분 앞으로 어떻게할지 정하는게 좋겠네요!

2022-08-22 05:11 UTC, tooooo1 commented on pages/auth/signIn.tsx
> +  padding-bottom: ${({ right }) => right && '1rem'};
오 좋아요 조건

2022-08-22 05:11 UTC, tooooo1 commented on pages/auth/signIn.tsx
> +  gap: 0.5rem;
good

2022-08-22 05:11 UTC, tooooo1 commented on pages/auth/signIn.tsx
> +  line-height: 1.563rem;
이건 무슨 기준인가요? 소숫점 3자리까지 하셨길래

2022-08-22 05:11 UTC, tooooo1 commented on pages/auth/signUp.tsx
> +  gap: 0.688rem;
어떤 기준이 있는거같아요. 저도 알려주세요 ㅋㅋ 완전 디테일하네요

2022-08-25 04:54 UTC, blan19 commented on pages/auth/signIn.tsx
> +  line-height: 1.563rem;
요것도 피그마에 나온 픽셀기준으로 했는데 소수점까지 나왔네요 ㅋㅋㅋ...

2022-08-25 04:54 UTC, blan19 commented on pages/auth/signUp.tsx
> +  gap: 0.688rem;
모두다 피그마에 있는 css 픽셀 기준으로 했습니다 ㅋㅋㅋㅋㅌㅋㅋ

2022-08-25 04:55 UTC, blan19 commented on components/auth/styled.ts
> +const AuthRadioButton = styled(Radio)``;
요부분은 충일님이 얘기해주신것처럼 일단 기본 태그를 사용해서 반영할게요! 나중에 한꺼번에 처리할수있는 컴포넌트를 만들어서 처리하던가 해볼게요.. ㅋㅋㅋ

2022-08-27 05:26 UTC, tooooo1 commented on pages/auth/signUp.tsx
> +  gap: 0.688rem;
아 피그마 !

2022-08-27 05:26 UTC, tooooo1 approved these changes

2022-08-27 05:27 UTC, merged